### ISSUE TITLE
Panic at kldload related to iicbb_devclass

### ISSUE THREAD

**Issue by johalun** [FreeBSDDesktop/drm-legacy#11]
13.0-CURRENT as of June 6.
Can't really see the backtrace because of tiny screen, but it seems to be iicbb related at i915_attach.
@avg-I

**Comment by johalun** [comment]
Somewhere in  `intel_setup_gmbus`

**Comment by johalun** [comment]
Looks like something fails and it crashes at `device_delete_child -> device_detach` from `intel_setup_gmbus`

**Comment by avg-I** [comment]
Thank you and sorry about that.
