### ISSUE TITLE
Deprecation message even when using drm-legacy-kmod

### ISSUE THREAD

**Issue by adaugherity** [FreeBSDDesktop/drm-legacy#7]
I installed FreeBSD 12.0 and after `kldload radeonkms`, saw a deprecation message:
```
info: [drm] Initialized drm 1.1.0 20060810
drmn0: =======================================================
drmn0: This code is obsolete abandonware. Install the graphics/drm-legacy-kmod pkg
drmn0: =======================================================
drmn0: Deprecated code (to be removed in FreeBSD 13): drm2 drivers
drmn0: =======================================================
drmn0: This code is obsolete abandonware. Install the graphics/drm-legacy-kmod pkg
drmn0: =======================================================
drmn0: Deprecated code (to be removed in FreeBSD 13): drm2 drivers
drmn0: <ATI ES1000 RN50> on vgapci0
[...]
````
I installed this package as directed and followed [its directions](https://svnweb.freebsd.org/ports/head/graphics/drm-legacy-kmod/pkg-message?revision=484330&view=markup):
> Simply add kld_list="/boot/modules/[driver].ko to /etc/rc.conf, for example
[...] kld_list="/boot/modules/radeonkms.ko" for the ATI/AMD GPU driver.

After doing so, I _still_ get the deprecation message seen above.  Turns out, it was using `radeonkms.ko` from this path but the `drm2.ko` dependency was loaded from the built-in `/boot/kernel/drm2.ko`.  To get rid of the deprecation warning entirely, you must load **both** drm2 and the GPU driver from /boot/modules, e.g.:
```
kld_list="/boot/modules/drm2.ko /boot/modules/radeonkms.ko"
```

I don't know if the GPU drivers can be built to load DRM from the modules directory rather than /boot/kernel, but if not, the documentation needs updating.

**Comment by zeising** [comment]
I have never seen this issue myself, but I guess it would make sense. I don't think the loader got fixed, and in any case, that fix is not in 12.0.

**Comment by zeising** [comment]
See also: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237127

**Comment by zeising** [comment]
I don't think we can change this from here. This is how the FreeBSD kernel module loader works.  To be sure the module from /boot/modules is loaded, you have to specify it in kld_list in rc.conf.

**Comment by adaugherity** [comment]
That's an understandable limitation, but the documentation needs to reflect that!

Someone mentioned updating the pkg-message file in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237127#c1, but that bug was closed without anyone doing so.  I just checked [svn](https://svnweb.freebsd.org/ports/head/graphics/drm-legacy-kmod/pkg-message?revision=508837&view=markup) and there's still no mention of `/boot/modules/drm2.ko` there.
